### ISSUE TITLE
Regression: mouse-wheel zooming broken in 3.2

### ISSUE THREAD

**Issue by rpavlik** [VUE/VUE#10]
See https://vue-forums.uit.tufts.edu/posts/list/1273.page

A potential place to look, based purely on commit messages, might be https://github.com/VUE/VUE/commit/d5da159228ac2c8cb3833f0dce2d0c265268f6a1#commitcomment-6159303

**Comment by rpavlik** [comment]
Any update on when 3.2.3 might be released?

**Comment by pplatek** [comment]
ALT+(mouse wheel) and (right mouse button)+(mouse wheel) zoom works in 3.3.0
