### ISSUE TITLE
cannot close split screen or open VUE maps

### ISSUE THREAD

**Issue by rcrath** [VUE/VUE#24]
Manjaro (arch based) Linux, up to date, VUE 3.3

problem:
1. vue 3.3  opens as split screen  (see screenshot). the right screen is a mirror of the left screen but smaller.
2. Toggling split screen in view menu has no effect. unable to remove the split, even though resize handle appears on mouse over.  can make the split bigger.  The arrow that made the split disappear in 3.22 is not present either.
3. Unable to close the new file on the right window.  able to seemingly close it on left, but then VUE left unusable.  Opening VUE maps fails.
4. trying to open a VUE map freezes VUE.
5. seems to be related to #14, which was still an issue in VUE 3.22 for me. but workaround of closing the blank file before opening an old one does not work.  Vue Freezes.

workaround:
Option 1: downgrade to 3.22 and use workaround for #14 
Option 2: open VUE, create a new node on the blank map (which will appear on both sides of the split if you do ctrl-] on the right pane), then open your file.  You will still have the asymmetrical mirrored split though.

This seems to only be a problem with the jar file version I guess (don't have windows or a mac)

![screenshot-window-2015-11-19-192156](https://cloud.githubusercontent.com/assets/944636/11292541/ad7b4b0e-8ef3-11e5-8805-dfd4a4b50378.png)

**Comment by MicroJoe** [comment]
I cannot reproduce the close split problem (steps 1 and 2), you may want to disable your GTK theme in Java to see the split arrows appear as shown in this screenshot:

![vue_close_split](https://cloud.githubusercontent.com/assets/989521/14444992/d7504f66-0049-11e6-9204-ab7297b69ed9.png)

I don't think I use this software at its full potential because I never show and use the right panel but I think it can become useful when you start to have big maps so I don't know about the close in right panel problem.

However I was able to reproduce the "you have to close default document before openning a VUE" part but as you said this problem was already here in 3.22 so I think I am going to keep the latest version in AUR for the moment unless you have other bugs to show me.

**Comment by rcrath** [comment]
Hi @MicroJoe, Thanks for looking at this.

Are you running the jar file from a linux command line to start? The issue may be particular to that configuration.  

The arrows for split screen show fine in 3.2.2, and the split window does not respond to menu commands either, so I am thinking it is something besides a general java config issue, but I tried as far as I could get with checking the java look and feel.  

I don't have gtk themes enables as far as I can tell.  I do have a font fix that I use in .bashrc to keep the chroma/irridescence problem down:

```
#java font fix
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=lcd'
#all options
# yoff, false, default	No anti-aliasing
# on	Full anti-aliasing
# gasp	Use the font's built-in hinting instructions
# lcd, lcd_hrgb	Anti-aliasing tuned for many popular LCD monitors
# lcd_hbgr, lcd_vrgb, lcd_vbgr	Alternative LCD monitor setting
#To optionally to use GTK look and feel, add the following line NSTEAD
#_JAVA_OPTIONS='-Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel' 
```
I have had the last line commented out the whole time.

Could the first line be the cause?
I tried this in .bashrc based on the oracle documentation pages, but it had no effect.  Not sure I read the instructions right:

```
_JAVA_OPTIONS='-Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.CrossPlatformLookAndFeel'
``` 
followed by 
```
$ source .bashrc
```

**Comment by MicroJoe** [comment]
> Are you running the jar file from a linux command line to start? The issue may be particular to that configuration.

I am running the jar from the command line with a `java -jar VUE.jar` when I start it manually. But now I have a script like this:

```sh
#!/bin/sh

exec java -jar VUE.jar
```

That I start using `dmenu` so I think it can be considered as "command line" because I am not using desktop files or anything that fancy.

The first line is not a problem because I have the same settings (put inside `/etc/environment`):

```
$ java
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=lcd
...
```

> I don't have gtk themes enables as far as I can tell.

If we compare our two screenshots you can see that mine looks "the default Swing theme" whereas yours looks like GTK themed so maybe it is your distro or your desktop manager that is doing that so it's maybe the reason you cannot see the arrows (but not sure at all, not a big fan of Java stuff).

The `gtk` part in your look & feel seems strange. [The documentation](https://docs.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html) is speaking about `javax.swing.plaf.metal`. Also you forgot the `export` part.

Try:

```
export _JAVA_OPTIONS='-Dswing.defaultlaf=com.sun.java.swing.plaf.metal.CrossPlatformLookAndFeel'
```

Or retry your option with the export.

**Comment by Hans-Maulwurf** [comment]
I have the same behaviour lice rcrath. With the last export option, i get the following error:

`Exception in thread "main" java.lang.Error: Cannot load com.sun.java.swing.plaf.metal.CrossPlatformLookAndFeel
	at javax.swing.UIManager.initializeDefaultLAF(UIManager.java:1351)
	at javax.swing.UIManager.initialize(UIManager.java:1459)
	at javax.swing.UIManager.maybeInitialize(UIManager.java:1426)
	at javax.swing.UIManager.getUI(UIManager.java:1006)
	at javax.swing.JViewport.updateUI(JViewport.java:317)
	at javax.swing.JViewport.<init>(JViewport.java:277)
	at javax.swing.JScrollPane.createViewport(JScrollPane.java:927)
	at javax.swing.JScrollPane.<init>(JScrollPane.java:298)
	at javax.swing.JScrollPane.<init>(JScrollPane.java:323)
	at edu.tufts.vue.preferences.generics.GenericListPreference.<init>(GenericListPreference.java:44)
	at edu.tufts.vue.preferences.implementations.LanguagePreference.<init>(LanguagePreference.java:62)
	at edu.tufts.vue.preferences.implementations.LanguagePreference.create(LanguagePreference.java:50)
	at tufts.vue.VueResources.<clinit>(VueResources.java:85)
	at tufts.vue.SearchTextField.<clinit>(SearchTextField.java:88)
	at tufts.vue.VUE.<clinit>(VUE.java:175)`

system: arch linux (antergos) with gnome

btw: is there still active development on VUE?

**Comment by MicroJoe** [comment]
Last commit was on Oct. 2015 so we are only speaking between users here because the project seems to be not maintained anymore (or at least on GH). One should look on their forums to see what's going on for this software.

@Hans-Maulwurf try `javax.swing.plaf.metal.MetalLookAndFeel` (see <https://docs.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html>)

**Comment by rcrath** [comment]
@Hans-Maulwurf I think the development is sporadic.  I have been using VUE for several years, and the devs are as quiet on the user forum as they are here. Probably overworked and underpaid :)  I raised #14 there first, then came here hoping there might be more attention.  But just when I thought there was nothing happening, 3.3 got released.  ( @mkorcy - Mike Korcynski at Tufts -- looks like the lead dev, and probably has a ton of stuff to do elsewhere!).  It is an excellent project, and I have turned a few dozen students into avid VUE users, so I hope it keeps developing.  WIsh I could code to contribute, but don't know how.  

@MicroJoe I am guessing, and totally into trying to sort this out, but I am still not sure it is my settings that are the problem, since the problem does not occur in VUE 3.2.2, only in 3.3.0. If it were general instead of app specific problem, I would have the window decoration missing icon problem in both cases but it is only missing in 3.3. 

I followed your suggestions though. I fixed the export statement and tried several LAF settings including the one you said, both with and without the hinting setting, and got the same window issues: second window showing, no screen controls on the second window, as in the screen shots, no similar problem in 3.2.2, which decorated its single window properly.  In addition, I noticed I got a different file open dialog (which I don't like -- it seems a cross between  windows 3.1 and OS9 three-column finder mode with one less column!).  I also got an error saying I could not write to the java prefs directory on both open and close of the app when I ran it from CL. I tried creating the directories and pointing VUE at them using [this advice](http://www.reversexsl.com/j/index.php?option=com_content&task=view&id=44&Itemid=65), but it did not work. 

Then I guessed it might be some kind of permissions issue since the files could not be written, so I ran VUE as root.  While the fonts where ugly and the font  hinting was gone, VUE started with a single window and the proper icons.  It worked properly except for #14, (which is a separate issue that was present in 3.2.x) including having the old style file open dialog.  After running as root, I could run as my normal user and the file access errors were gone, but the problem with the extra window, no icons, and the new open file dialog remained.  

SO somewhere, my user preferences are causing a whole different LAF, including fonts, to be loaded when I start VUE as a normal user as opposed to root.  Or else root is allowed to R/W some files that I cannot access as user.  Maybe dev developed it in an admin account?

I also ran from command line instead of starting via desktop file.  Here is the output running 3.3.0 as a normal user -- maybe it contains clues?

```
rich[VUE]$ java -jar VUE33.jar
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=lcd
VUE 2016-05-02 15:57:05,471  INFO [main] VUE: VUE build: October 8 2015 at 1658 by tomadm on Linux 2.6.32-504.23.4.el6.x86_64 i386 JVM 1.7.0_21-b11(bits=32)
VUE 2016-05-02 15:57:05,471  INFO [main] VUE: Current Platform: Linux 4.4.8-1-MANJARO amd64
VUE 2016-05-02 15:57:05,475  INFO [main] VUE: Running JVM: 1.8.0_92-b14 / 64 bit; MaxMemory(-Xmx)=3556.0M, CurMemory(-Xms)=303.0M, FreeMemory=270.3M
VUE 2016-05-02 15:57:05,475  INFO [main] VUE: VUE version: 3.3.0
VUE 2016-05-02 15:57:05,475  INFO [main] VUE: Current Working Directory: /home/rich/bin/VUE
VUE 2016-05-02 15:57:05,475  INFO [main] VUE: User/host: rich@null
VUE 2016-05-02 15:57:06,173  INFO [main] [init] Images: created thread pool: tufts.vue.Images$PriorityThreadPool@318ba8c8[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]; maxSize=7
VUE 2016-05-02 15:57:07,693  INFO [main] [init] [build] RDFIndex: "http://vue.tufts.edu/ontology/vue.rdfs#" <- VUE_ONTOLOGY
VUE 2016-05-02 15:57:07,693  INFO [main] [init] [build] RDFIndex: "http://vue.tufts.edu/vue.rdfs#" <- VUE_GENERAL_NAMESPACE
VUE 2016-05-02 15:57:07,693  INFO [main] [init] [build] RDFIndex: "http://vue.tufts.edu/vue.rdfs#none" <- ONTOLOGY_NONE java.lang.String@7205765b
VUE 2016-05-02 15:57:07,693  INFO [main] [init] [build] VueMetadataElement: ONTOLOGY_NONE "http://vue.tufts.edu/vue.rdfs#none" java.lang.String@7205765b
VUE 2016-05-02 15:57:07,750  INFO [main] [init] [build] MetadataList: ONTOLOGY_NONE "http://vue.tufts.edu/vue.rdfs#none" java.lang.String@7205765b
VUE 2016-05-02 15:57:08,910  INFO [main] [init] [build] Mapping: Loading mapping descriptors from jar:file:/home/rich/bin/VUE/VUE33.jar!/tufts/vue/resources/lw_mapping_1_1.xml
VUE 2016-05-02 15:57:10,486  INFO [Thread-2] CategoryModel: no custom meta-data: /home/rich/.vue_2/custom.rdfs (No such file or directory)
VUE 2016-05-02 15:57:12,088  WARN [main] [init] [build] EditorManager: editor not ready to produce value: tufts.vue.FontEditorPanel$17@782a4fff[tufts.vue.FontEditorPanel$17:LWPropertyHandler[font.style=java.lang.NullPointerException]]; java.lang.NullPointerException
VUE 2016-05-02 15:57:12,089  WARN [main] [init] [build] EditorManager: editor not ready to produce value: tufts.vue.FontEditorPanel$18@05ae81e1[tufts.vue.FontEditorPanel$18:LWPropertyHandler[font.underline=java.lang.NullPointerException]]; java.lang.NullPointerException
java.lang.ArrayIndexOutOfBoundsException: No such child: 1; in Thread[main,5,main] at 1462240632531 Mon May 02 15:57:12 HST 2016
	at java.awt.Container.getComponent(Container.java:334) 
	at tufts.vue.VUE$29.addNotify(VUE.java:2847) 
	at java.awt.Container.addImpl(Container.java:1121) 
	at java.awt.Container.add(Container.java:973) 
	at tufts.vue.gui.VueFrame.addComp(VueFrame.java:351) 
	at tufts.vue.VUE.buildApplicationInterface(VUE.java:1641) 
	at tufts.vue.VUE.initApplication(VUE.java:1302) 
	at tufts.vue.VUE.main(VUE.java:1063) 
END java.lang.ArrayIndexOutOfBoundsException: No such child: 1

VUE 2016-05-02 15:57:12,776  WARN [main] [init] [build] LWComponent: setCreated erasing 1462240632773=Mon May 02 15:57:12 HST 2016 with: 1462240632776=Mon May 02 15:57:12 HST 2016; LWMap[v-1 New Map n=0]
VUE 2016-05-02 15:57:12,780  INFO [main] [init] [build] VUE: displayMap LWMap[v-1 New Map n=1]
VUE 2016-05-02 15:57:13,058  WARN [main] [init] LayersUI: getActiveLayer when map is null
VUE 2016-05-02 15:57:13,058  INFO [main] VUE: UI startup completed.
VUE 2016-05-02 15:57:14,033  INFO [main] [initDS] UrlAuthentication: instanced; listening to VDSM
VUE 2016-05-02 15:57:14,033  INFO [main] [initDS] VueDataSourceManager: Installed DataSources not found; missing /home/rich/.vue_2/InstalledDataSources.xml
VUE 2016-05-02 15:57:14,033  INFO [main] [initDS] VueDataSourceManager: configuring data sources; n=0
VUE 2016-05-02 15:57:14,033  INFO [main] [initDS] VueDataSourceManager: Installed DataSources not found; missing /home/rich/.vue_2/InstalledDataSources.xml
VUE 2016-05-02 15:57:14,177  INFO [main] VUE: main complete
VUE 2016-05-02 15:57:17,264  INFO [AWT-EventQueue-0] MapViewer: pre-cache run "New Map": java.util.LinkedHashSet@78cd8190[size=0]
VUE 2016-05-02 15:57:17,633  INFO [AWT-EventQueue-0] [DSV] DataSourceViewer: requesting installed data sources from VDSM
VUE 2016-05-02 15:57:17,633  INFO [AWT-EventQueue-0] [DSV] VueDataSourceManager: Installed DataSources not found; missing /home/rich/.vue_2/InstalledDataSources.xml
VUE 2016-05-02 15:57:19,048  INFO [AWT-EventQueue-0] [DSV] VueFederatedSearchManager: listing /Library/Caches/OSID to find "Extensions.xml"
VUE 2016-05-02 15:57:20,478  INFO [AWT-EventQueue-0] [DSV] DataSourceViewer: Loading old style data sources...
VUE 2016-05-02 15:57:22,569  INFO [AWT-EventQueue-0] [DSV] DataSourceViewer: Loaded old style data sources.
VUE 2016-05-02 15:57:23,033  INFO [version-check] VUE: Checking for latest version of VUE
VUE 2016-05-02 15:57:30,798  WARN [AWT-EventQueue-0] VueFrame: java.awt.event.WindowEvent[WINDOW_CLOSING,opposite=null,oldState=0,newState=0] on VueFrame0
VUE 2016-05-02 15:57:30,845  INFO [AWT-EventQueue-0] ExitAction: Exiting...
VUE 2016-05-02 15:57:30,847  INFO [AWT-EventQueue-0] ExitAction: Exiting VUE.
```

**Comment by andersjohansson** [comment]
I experience the same issues.
In 3.3.0, from release notes

> changes LAF for linux to use SystemLAF which should behave better 
https://vue-forums.uit.tufts.edu/posts/list/1419.page

That is, in 3.3.0 we get GTK-styling (or whatever) by default if we don't change it with options. "Should behave better" is really not always the case...

**Comment by andersjohansson** [comment]
Oh, and it seems it doesn't work to change the laf from commandline either. With:

    -Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel'

I still get the GTK look and feel in VUE.

**Comment by andersjohansson** [comment]
Running as root "worked" for me as well. When running as an unprivileged user, I get the similar output as @rcrath. The difference to the root output is this exception:

````
java.lang.ArrayIndexOutOfBoundsException: No such child: 1; in Thread[main,5,main] at 1523006894011 Fri Apr 06 11:28:14 CEST 2018
	at java.awt.Container.getComponent(Container.java:334) 
	at tufts.vue.VUE$29.addNotify(VUE.java:2847) 
	at java.awt.Container.addImpl(Container.java:1122) 
	at java.awt.Container.add(Container.java:973) 
	at tufts.vue.gui.VueFrame.addComp(VueFrame.java:351) 
	at tufts.vue.VUE.buildApplicationInterface(VUE.java:1641) 
	at tufts.vue.VUE.initApplication(VUE.java:1302) 
	at tufts.vue.VUE.main(VUE.java:1063) 
END java.lang.ArrayIndexOutOfBoundsException: No such child: 1
````
Which is indeed the drawing of the split panes (see: https://github.com/VUE/VUE/blob/3.3.0/VUE2/src/tufts/vue/VUE.java#L1641 `mViewerSplit` is a `javax.swing.JSplitPane`). I have no idea why this happens though.

**Comment by andersjohansson** [comment]
Calling it like this actually works for me:
````
java -Dswing.systemlaf=javax.swing.plaf.metal.MetalLookAndFeel -jar VUE.jar
````
So. Not setting `defaultlaf` but setting `systemlaf`!
Got that from here:
https://stackoverflow.com/questions/33735981/java-in-linux-different-look-and-feel-classes-for-root-and-non-root

Metal is very ugly though and Nimbus looks better:
````
java -Dswing.systemlaf=javax.swing.plaf.nimbus.NimbusLookAndFeel -jar VUE.jar
````

**Comment by rcrath** [comment]
@andersjohansson thanks that.  Can now run VUE 3.3 without the split window problem.  The having to close the startup map before opening a new one bug remains.
