### ISSUE TITLE
file associations misdirected

### ISSUE THREAD

**Issue by rcrath** [VUE/VUE#41]
WHen I click on a libreoffice .odt file, instead of opening LibreOffice, it tries to open the file in Firefox, which is not even the default browser.  In the xml, it shows as a URI.  Is their anyway to set the file association back to libreoffice?  I looked through the various google results, but VUE seems to have its own file association method outside the usual linux xdg-open and mimelist approaches, as witnessed by the non-default use of firefox.  I searched for file associations in java, but it was all coding stuff, and I could find nothing relevant in VUE prefs either.  ANy help appreciated!

**Comment by mkorcy** [comment]
It cascades through gnome-ope / kfmclient / firefox, it was written a while ago obviously, changing it to xdg-open makes sense though.

**Comment by rcrath** [comment]
following fixed it for me:

```
sudo ln -s /usr/bin/xdg-open /usr/bin/gnome-open
```
