### ISSUE TITLE
An error while trying to save a map

### ISSUE THREAD

**Issue by mili-ae** [VUE/VUE#55]
Hi. I am getting an error when trying to save my maps in .vue or .vpk formats 

OS: Fedora 34 5.13.13-200.fc34.x86-64

`VUE 2021-09-09 14:27:40,195 ERROR [AWT-EventQueue-0] [DSV] SaveAction: Exception attempting to save file /home/mili_ae/Desktop/New Map1.vue: java.lang.RuntimeException: Could not instantiate serializer com.sun.org.apache.xml.internal.serialize.XMLSerializer: java.lang.IllegalAccessException: class org.exolab.castor.xml.XercesJDK5Serializer cannot access class com.sun.org.apache.xml.internal.serialize.XMLSerializer (in module java.xml) because module java.xml does`

Is there any fix or workarounds about this problem?

**Comment by chreko** [comment]
You have to use Java 15 or earlier for this specific application. For example:
'sudo dnf install java-11-openjdk'
